// Copyright (c) 2019 TeepCo

#if !canImport(ObjectiveC)
    import XCTest

    extension StoolTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__StoolTests = [
            ("testMethod", testMethod),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(StoolTests.__allTests__StoolTests),
        ]
    }
#endif
